listen:
  port: 8080

servers:
  - host: 127.0.0.1
    port: 8001
    sidecar_port: 9001
    type: sinkhole
  - host: 127.0.0.1
    port: 8002
    sidecar_port: 9002
    type: sinkhole
  - host: 127.0.0.1
    port: 8003
    sidecar_port: 9003
    type: sinkhole
  - host: 127.0.0.1
    port: 8004
    sidecar_port: 9004
    type: sinkhole
  - host: 127.0.0.1
    port: 8005
    sidecar_port: 9005
    type: sinkhole-random
  - host: 127.0.0.1
    port: 8006
    sidecar_port: 9006
    type: sinkhole-random
  - host: 127.0.0.1
    port: 8007
    sidecar_port: 9007
    type: sinkhole-random
  - host: 127.0.0.1
    port: 8008
    sidecar_port: 9008
    type: sinkhole-random
  - host: 127.0.0.1
    port: 8009
    sidecar_port: 9009
    type: simulated-pause
  - host: 127.0.0.1
    port: 8010
    sidecar_port: 9010
    type: simulated-pause
  - host: 127.0.0.1
    port: 8011
    sidecar_port: 9011
    type: simulated-pause
  - host: 127.0.0.1
    port: 8012
    sidecar_port: 9012
    type: simulated-pause
  - host: 127.0.0.1
    port: 8013
    sidecar_port: 9013
    type: java-gc
  - host: 127.0.0.1
    port: 8014
    sidecar_port: 9014
    type: java-gc
  - host: 127.0.0.1
    port: 8015
    sidecar_port: 9015
    type: java-gc
  - host: 127.0.0.1
    port: 8016
    sidecar_port: 9016
    type: java-gc
